-intstyle "ise" -incremental -lib "unisims_ver" -lib "unimacro_ver" -lib "xilinxcorelib_ver" -o "C:/TTVM/sang_dich/test1_isim_beh.exe" -prj "C:/TTVM/sang_dich/test1_beh.prj" "work.test1" "work.glbl" 
